### ISSUE TITLE
Isambard Icelake Node Recognised as Cascadelake

### ISSUE THREAD

**Issue by kaanolgu** [archspec/archspec-json#78]
I am trying to use Spack on Isambard with git clone from the original repository. When I login to icelake partition, and execute the `spack arch` command it prints out `cray-rhel8-cascadelake `instead of `cray-rhel8-icelake` is there any fix for this ? Also when I try to use target=icelake it says
`spack install zlib target=icelake`
```
==> Error: concretization failed for the following reasons:

   1. cannot satisfy a requirement for package 'zlib'.
```
Spack Version  : `0.21.0.dev0 (646e7b4b007ccb2fd58742e9acc43faf7f491530)`

**Comment by tomgreen66** [comment]
Just want to comment - this is due to a limitation in the Cray Programming Modules on the system not with archspec or Spack.

**Comment by alalazo** [comment]
> Also when I try to use target=icelake it says [ ... ]

Try using:
```
spack config add concretizer:targets:host_compatible:false
```

**Comment by alalazo** [comment]
@tomgreen66 Thanks for the comment. Can you give a bit more insight into how Cray Modules influence this?

**Comment by tomgreen66** [comment]
If you take a look in https://github.com/spack/spack/blob/develop/lib/spack/spack/platforms/cray.py you will see:
 https://github.com/spack/spack/blob/aa39465188c6c0c29ebac0fd3e315d17473dcfee/lib/spack/spack/platforms/cray.py#L64-L67
 
 where it find the modules which are available for possible targets.  It doesn't find an Icelake module but does find cascade lake module.  Unfortunately due to the nature of Isambard having a Multi-Archtiecture Comparison System (MACS) the possible upgrade routes to support all architectures for the programming environments have certain limits and in this case we couldn't upgrade the Cray modules to support Icelake and was going to take a look when we migrate to Isambard 3 (where we will have production Grace-Grace system) and review what nodes can migrate across.  

Does that make sense?

**Comment by alalazo** [comment]
I'm closing this since it seems not related to `archspec`, but let me know if there's anything that should be revisited.
